version: "3.9"
services:
  auth-server:
    container_name: auth-server
    build: ./auth-server
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./auth-server/src/app:/app/src/app
    depends_on:
      - mongo
  # urr-service:
  #   container_name: urr-service
  #   build: ./urr-service
  #   expose:
  #     - 3004
  #   ports:
  #     - 3004:3004
  #   volumes:
  #     - ./urr-service/src/app:/app/src/app
  #   depends_on:
  #     - mongo
  auth-client:
    container_name: auth-client
    build: ./auth-client
    expose:
      - 3001
    ports:
      - 3001:3001
  urr-client:
    container_name: urr-client
    build: ./urr-client
    expose:
      - 3002
    ports:
      - 3002:3002
  mongo:
    image : mongo
    container_name: mongodb
    volumes:
      - ./.db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: unless-stopped

